[Unit]
ConditionPathExists=/etc/hafthios-installed
Conflicts=getty@tty1.service
After=systemd-user-sessions.service plymouth-start.service hafthios-package-keys.service

[Service]
ExecStartPre=-/usr/bin/plymouth quit --retain-splash
